// import Providers from "./provider";
// import { Poppins } from "next/font/google";
// import "./global.css";
// import Header from "./shared/componennts/Header/Header";
// import ReduxProvider from "./store/ReduxProvider";

// export const metadata = {
//   title: "Eshop Seller",
//   description: "Generated by create-nx-workspace",
// };

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`min-h-screen font-sans antialiased bg-[#FBF9F6] text-[#191817] ${poppins.variable}`}
//       >
//         <ReduxProvider>
//           <Providers>
//             <Header />
//             <main className="max-w-7xl mx-auto px-6 py-6">{children}</main>
//           </Providers>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }

import Providers from "./provider";
import { Poppins } from "next/font/google";
import "./global.css";
import Header from "./shared/componennts/Header/Header";
import ReduxProvider from "./store/ReduxProvider";
import { useAppSelector, useAppDispatch } from "./store/hook";
import { RootState } from "./store";
import { closeCart } from "./store/slices/cartSlice";
import CartSidebar from "./shared/componennts/CardSidebar/CartSidebar";

export const metadata = {
  title: "Eshop Seller",
  description: "Generated by create-nx-workspace",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen font-sans antialiased bg-[#FBF9F6] text-[#191817] ${poppins.variable}`}
      >
        <ReduxProvider>
          <Providers>
            <Header />
            <main className="max-w-7xl mx-auto px-6 py-6">{children}</main>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}

// Separate client component to handle sidebar UI
