import Providers from "./provider";
import { Poppins, Inter, Roboto } from "next/font/google";

import "./global.css";
import Header from "./shared/componennts/Header/Header";
import ReduxProvider from "./store/ReduxProvider";
import { Toaster } from "sonner";

import Footer from "./shared/componennts/Footer/Footer";
import ClientPushWrapper from "./ClientPushWrapper";
export const metadata = {
  title: "Eshop Seller",
  description: "Generated by create-nx-workspace",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Example: request token on load

  return (
    <html lang="en">
      <body
        className={`min-h-screen font-sans antialiased bg-[#FBF9F6] text-[#191817] ${poppins.variable} ${inter.variable} ${roboto.variable}`}
      >
        <ReduxProvider>
          <Providers>
            <Header />
            <ClientPushWrapper />
            <main className="max-w-7xl mx-auto px-6 py-6">{children}</main>
            <Toaster richColors position="top-right" />
            <Footer />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
