import { SizeOptions } from "@/commons/components/ProductCard/ProductCard.types";
import { ProductEntity } from "@/commons/domain/entities/ProductEntity";
const sizeOptions: SizeOptions[] = [
  {
    label: "120 ML",
    price: 4150,
  },
  {
    label: "250 ML",
    price: Math.floor(Number(4150 * 1.3)),
  },
  {
    label: "500 ML",
    price: Math.floor(Number(4150 * 1.5)),
  },
];
export const productsData: ProductEntity[] = [
  {
    id: "vinoperfect_brightening_moisturizer",
    sku: "vinoperfect-brightening-moisturizer",
    category: "Bestseller",
    subCategory: "Moisturizer",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    price: 4150,
    size: sizeOptions,
    originalPrice: 4900,
    discount: "15% off",
    productImage: "/assets/images/ProductImageOne.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "hydra_essentiel_cream",
    sku: "hydra-essentiel-cream",
    category: "Moisturizer",
    subCategory: "Hydrating",
    sale: true,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3500,
    originalPrice: 4000,
    discount: "12% off",
    productImage: "/assets/images/ProductImageTwo.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 0,
  },
  {
    id: "watermelon_glow_niacinamide",
    category: "Bestseller",
    subCategory: "Serum",
    sale: false,
    brand: "GLOW RECIPE",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3200,
    originalPrice: 3200,
    discount: "",
    productImage: "/assets/images/ProductImageThree.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "advanced_night_repair_serum",
    category: "Bestseller",
    subCategory: "Anti-Aging",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    size: sizeOptions,
    price: 6500,
    originalPrice: 7200,
    discount: "10% off",
    productImage: "/assets/images/ProductImageFour.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    isHearted: false,
    stock: 10,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageFive.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "Beauty of Joseon",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageSix.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "vinoperfect_brightening_moisturizer",
    category: "Bestseller",
    subCategory: "Moisturizer",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    size: sizeOptions,
    price: 4150,
    originalPrice: 4900,
    discount: "15% off",
    productImage: "/assets/images/ProductImageOne.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 0,
  },
  {
    id: "hydra_essentiel_cream",
    category: "Moisturizer",
    subCategory: "Hydrating",
    sale: true,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3500,
    originalPrice: 4000,
    discount: "12% off",
    productImage: "/assets/images/ProductImageTwo.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "watermelon_glow_niacinamide",
    category: "Bestseller",
    subCategory: "Serum",
    sale: false,
    brand: "GLOW RECIPE",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3200,
    originalPrice: 3200,
    discount: "",
    productImage: "/assets/images/ProductImageThree.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "advanced_night_repair_serum",
    category: "Bestseller",
    subCategory: "Anti-Aging",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    size: sizeOptions,
    price: 6500,
    originalPrice: 7200,
    discount: "10% off",
    productImage: "/assets/images/ProductImageFour.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    isHearted: false,
    stock: 0,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageFive.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "Beauty of Joseon",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageSix.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "vinoperfect_brightening_moisturizer",
    category: "Bestseller",
    subCategory: "Moisturizer",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    size: sizeOptions,
    price: 4150,
    originalPrice: 4900,
    discount: "15% off",
    productImage: "/assets/images/ProductImageOne.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "hydra_essentiel_cream",
    category: "Moisturizer",
    subCategory: "Hydrating",
    sale: true,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3500,
    originalPrice: 4000,
    discount: "12% off",
    productImage: "/assets/images/ProductImageTwo.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "watermelon_glow_niacinamide",
    category: "Bestseller",
    subCategory: "Serum",
    sale: false,
    brand: "GLOW RECIPE",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 3200,
    originalPrice: 3200,
    discount: "",
    productImage: "/assets/images/ProductImageThree.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "advanced_night_repair_serum",
    category: "Bestseller",
    subCategory: "Anti-Aging",
    sale: true,
    brand: "CAUDALIE",
    productName: "Vinoperfect Instant Brightening Moisturizer",
    size: sizeOptions,
    price: 6500,
    originalPrice: 7200,
    discount: "10% off",
    productImage: "/assets/images/ProductImageFour.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    isHearted: false,
    stock: 10,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "SKIN 1004",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageFive.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
  {
    id: "tatcha_dewy_skin_cream",
    category: "Moisturizer",
    subCategory: "Bestseller",
    sale: false,
    brand: "Beauty of Joseon",
    productName:
      "Beauty of Joseon Matte Sun Stick Mugwort + Camelia With SPF 50 PA++++",
    size: sizeOptions,
    price: 5400,
    originalPrice: 5400,
    discount: "",
    productImage: "/assets/images/ProductImageSix.png",
    hoverImage: "/assets/images/BestSellerDummyImageHover.png",
    stock: 10,
  },
] as unknown as ProductEntity[];
